[app]
dingashost2 ansible_host=10.10.10.12
dingashost3 ansible_host=10.10.10.21

[database]
dingashost4 ansible_host=10.10.10.22

[log_servers]
dingashost4

[compliance]
dingashost4

[managed_nodes:children]
app
database
log_servers
compliance

[managed_nodes:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/home/dingane/.ssh/id_ed25519_lab
