#!/usr/bin/env python3

import getpass
import json
import subprocess
from pathlib import Path


BASE = Path.home() / "linux-lab" / "provisioning" / "kickstart"

TEMPLATE = BASE / "templates" / "rhel10-server.ks.tmpl"
INVENTORY = BASE / "inventory" / "hosts.json"

GENERATED = BASE / "generated"
HTTP_KS = BASE / "http-root" / "ks"

PUBLIC_KEY = Path.home() / ".ssh" / "id_ed25519_provisioning.pub"


def password_hash(prompt):
    """
    Prompt for a password without displaying it and return
    a SHA-512 crypt hash generated by OpenSSL.
    """

    first = getpass.getpass(prompt)
    second = getpass.getpass("Confirm password: ")

    if first != second:
        raise RuntimeError("Passwords do not match.")

    if not first:
        raise RuntimeError("Password cannot be empty.")

    result = subprocess.run(
        ["openssl", "passwd", "-6", "-stdin"],
        input=first + "\n",
        text=True,
        capture_output=True,
        check=True,
    )

    return result.stdout.strip()


def build_nat_network(host):
    """
    Return a Kickstart NAT/DHCP network stanza when the host
    has a NAT interface.

    Isolated systems receive no NAT configuration.
    """

    nat_interface = host.get("nat_interface")

    if not nat_interface:
        return "# No NAT interface configured for this host"

    return f"""network --device={nat_interface} --bootproto=dhcp --activate --onboot=on"""


def ensure_required_files():
    required = [
        TEMPLATE,
        INVENTORY,
        PUBLIC_KEY,
    ]

    for path in required:
        if not path.is_file():
            raise FileNotFoundError(
                f"Required file does not exist: {path}"
            )


def main():
    ensure_required_files()

    template = TEMPLATE.read_text(encoding="utf-8")

    hosts = json.loads(
        INVENTORY.read_text(encoding="utf-8")
    )

    public_key = PUBLIC_KEY.read_text(
        encoding="utf-8"
    ).strip()

    GENERATED.mkdir(
        parents=True,
        exist_ok=True,
    )

    HTTP_KS.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("Generating RHEL 10 Kickstart configurations.")
    print()

    root_hash = password_hash(
        "Enter local root password for provisioned systems: "
    )

    admin_hash = password_hash(
        "Enter dingane account password: "
    )

    print()

    for host_name, host in hosts.items():

        nat_network = build_nat_network(host)

        replacements = {
            "__HOSTNAME__": host["hostname"],
            "__MGMT_IP__": host["management_ip"],
            "__MGMT_INTERFACE__": host["management_interface"],
            "__NAT_NETWORK__": nat_network,
            "__SSH_PUBLIC_KEY__": public_key,
            "__ROOT_PASSWORD_HASH__": root_hash,
            "__ADMIN_PASSWORD_HASH__": admin_hash,
        }

        rendered = template

        for placeholder, value in replacements.items():
            rendered = rendered.replace(
                placeholder,
                value,
            )

        unresolved = [
            token
            for token in (
                "__HOSTNAME__",
                "__MGMT_IP__",
                "__MGMT_INTERFACE__",
                "__NAT_NETWORK__",
                "__SSH_PUBLIC_KEY__",
                "__ROOT_PASSWORD_HASH__",
                "__ADMIN_PASSWORD_HASH__",
            )
            if token in rendered
        ]

        if unresolved:
            raise RuntimeError(
                f"{host_name}: unresolved placeholders: "
                + ", ".join(unresolved)
            )

        generated_file = GENERATED / f"{host_name}.cfg"
        web_file = HTTP_KS / f"{host_name}.cfg"

        generated_file.write_text(
            rendered,
            encoding="utf-8",
        )

        web_file.write_text(
            rendered,
            encoding="utf-8",
        )

        generated_file.chmod(0o600)
        web_file.chmod(0o600)

        print(f"[OK] {host_name}")
        print(f"     role: {host['role']}")
        print(f"     IP:   {host['management_ip']}")
        print(f"     file: {generated_file}")

        if host.get("internet_connected"):
            print(
                f"     NAT:  {host['nat_interface']}"
            )
        else:
            print("     NAT:  none / isolated")

        print()


if __name__ == "__main__":
    main()
